[package]
name = "daze"
version = "0.1.0"
authors = ["mohanson <mohanson@outlook.com>"]
edition = "2018"

[dependencies]
argparse = "0.2"
byteorder = "1.2"
md5 = "0.6"
rc4 = { git = "https://github.com/rsdump/rc4" }
